package MiSuperEnHilos;

public enum Articulos {
	LECHE, HUEVO, YOGURES, POLLO, PAVO,
    ATUN, PATATA, LIMONES, PERAS, ARROZ,
    CERVEZA, TINTO, TE, CAFE, PASTA,
    PAN, AVENA, SALSA, ACEITE, SAL,
    FRIJOLES, VERDURAS, MERMELADA, MANTEQUILLA
}
